### ISSUE TITLE
Code style idea: seperate usages of callBy* that send value > 0 and those with value == 0

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#286]
As only ~3 or so instances of the CallBy methods use non zero value, there is a potential source of confusion around sending $ to the call.

Create two versions of each of the callBy* Methods that accept value and that expect value = 0. Most instances will use the value = 0 and the code should be more readable.

:link: [zboto Link](https://app.clickup.com/t/8677fnguv)

**Comment by emmanuelm41** [comment]
@snissn I know what you mean here, but so far we have **callByID**, **callByAddress** and **callNonSingletonByID**. If we add another option with = 0 and != 0, it is going to be kind of messy. I think we can sacrifice this in order to avoid more and more functions that are slightly different. I could add a constant called VALUE_ZERO and send that as value for methods that don't send anything. That could be an option.

**Comment by maciejwitowski** [comment]
@snissn is what you're proposing to have some `callWithValueByID` method? I'm not sure it's gonna be more readable. This is internal API anyway, right? We don't expect developers to be using these methods directly.

**Comment by snissn** [comment]
yes - this helps with long term code maintainability to prevent future development from problems, but is not needed for this release

**Comment by emmanuelm41** [comment]
We will end up with a long combination of functions that do almost the same though.

**Comment by snissn** [comment]
i'm happy to close this one
