### ISSUE TITLE
Test miner and market actors on wallaby

### ISSUE THREAD

**Issue by ainhoa-a** [Zondax/filecoin-solidity#72]
:link: [zboto Link](https://app.clickup.com/t/39qt9zr)

**Comment by emmanuelm41** [comment]
At this moment, we need this issue to be completed first https://github.com/Zondax/filecoin-solidity-api/issues/52. Methods won't work if we don't use `deletacall` instead of `staticcall`.

**Comment by emmanuelm41** [comment]
At this moment, we need this issue to be completed first https://github.com/Zondax/filecoin-solidity/pull/110.

**Comment by rllola** [comment]
This should be unblocked now. #110 has been merged

**Comment by emmanuelm41** [comment]
Great! Thanks! I will work on this during the day!

**Comment by emmanuelm41** [comment]
Task blocked until 9th January...

"we will take down Wallabynet on Friday 6th of January 2023 for extended maintenance - 00:01 UTC
Should everything be ready on the 9th this"

**Comment by emmanuelm41** [comment]
I have tested some specific methods manually and they were working correctly. This issue should be discussed further in order to fin a way to run tests from CI on wallaby. We are not currently able to test the entire set of methods as many needs specific scenarios on wallaby (miner addresses, verified ones, etc). But for now I don't think we can do more manually than what I did.
